### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by kamelelrefaie** [kamelelrefaie/RickAndMorty#1]
https://user-images.githubusercontent.com/52335429/147242351-ba653bb5-4c69-4234-9a29-c05692d32ce4.mp4

**Comment by MahmoudMabrok** [comment]
if u add video to be used with README, you can safely delete this issue or close it

and link will still valid.

**Comment by kamelelrefaie** [comment]
> if u add video to be used with README, you can safely delete this issue or close it
> 
> and link will still valid.

okay, thank you
